### ISSUE TITLE
Can't split horizontal correct

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#10]
When i type "C-x 2"  to split horizontal,  external app windows can't adjust size....

**Comment by tumashu** [comment]
It make "ivy" and "ido-vectal-mode" useless...

**Comment by Necronian** [comment]
C-x 2 works for me but I do have the issues with ido-vertical. I was trying to
figure fix it this morning, running exwm-layout--refresh manually when the
vertical buffer is open resizes the window correctly. I just don't know where
to hook it in order to run it at the appropriate time.

The minibuffer-setup-hook runs before the minibuffer is displayed and resized. (obviously)

The window-size-change-function seems to fire after the minibuffer is closed.

**Comment by tumashu** [comment]
exwm的理念突然让我想到了火影忍者中的傀儡术。。。。太有才了。。。。

**Comment by ch11ng** [comment]
I tihnk `split-window-*` commands is working here. Perhaps the behavior was caused by some other package you enabled.

As for the issue with `ido-vertical-mode`, there is no way but to resize the minibuffer accordingly. Currently, `exwm-layout--refresh` is run in `window-configuration-change-hook` but could be changed to use `buffer-list-update-hook` instead (with some extra overhead of course). A better way would be to introduce an extra dedicated minibuffer frame (with frame parameter `(minibuffer . only)`) and redirect all key events to it. Then there is no need to resize the windows. I'm waiting to see if someone can come up with an alternative solution.

**Comment by tumashu** [comment]
I tested，but can't find the problem

**Comment by tumashu** [comment]
"split-window-*" works for me...

**Comment by ch11ng** [comment]
Does the "`C-x 2`" problem still persist after all other packages are disabled?

**Comment by tumashu** [comment]
```
A better way would be to introduce an extra dedicated minibuffer frame (with frame parameter (minibuffer . only)) and redirect all key events to it. Then there is no need to resize the windows. I'm waiting to see if someone can come up with an alternative solution.
```
another way is  when minibuffer lines > 1 , temporary hide all external windows and only show emacs frame.

**Comment by tumashu** [comment]
I find `post-command-hook‘， can partily solve this problem。。。

**Comment by tumashu** [comment]
Test like this：
```
(defun exwm-layout--init ()
  "Initialize layout module."
  ;; Auto refresh layout
  (add-hook 'window-configuration-change-hook 'exwm-layout--refresh)
  (add-hook 'post-command-hook 'exwm-layout--refresh))
```

**Comment by Necronian** [comment]
That semi fixes ido-vertical-mode. On invocation the minibuffer is still hidden behind windows but any action will cause the window to resize correctly.

**Comment by tumashu** [comment]
A hack solution

```
(defvar eh-exwm-monitor-minibuffer-timer nil)
(defun eh-exwm-monitor-minibuffer ()
  (when eh-exwm-monitor-minibuffer-timer
    (cancel-timer eh-exwm-monitor-minibuffer-timer))
  (setq eh-exwm-monitor-minibuffer-timer
        (run-with-timer nil 0.2
                        #'(lambda ()
                            (when (or (not ido-exit)
                                      (not ivy-exit))
                              (exwm-layout--refresh))))))

(eh-exwm-monitor-minibuffer)

```

**Comment by Necronian** [comment]
This is what I now have in my exwm-layout.el 
It works for me. I don't know if it makes sense or is a good idea my elisp is pretty weak.

```elisp
(defvar eh-exwm-monitor-minibuffer-timer nil)

(defun eh-exwm-cancel-monitor-minibuffer ()
  (when eh-exwm-monitor-minibuffer-timer
    (cancel-timer eh-exwm-monitor-minibuffer-timer)
    (setq eh-exwm-monitor-minibuffer-timer nil)))

(defun eh-exwm-monitor-minibuffer ()
  (eh-exwm-cancel-monitor-minibuffer)
  (setq eh-exwm-monitor-minibuffer-timer
        (run-with-timer 0.01 0.2
                        #'(lambda () (exwm-layout--refresh)))))

(defun exwm-layout--init ()
  "Initialize layout module."
  ;; Auto refresh layout
  (add-hook 'window-configuration-change-hook 'exwm-layout--refresh)
  (add-hook 'minibuffer-setup-hook 'eh-exwm-monitor-minibuffer)
  (add-hook 'minibuffer-exit-hook 'eh-exwm-cancel-monitor-minibuffer))
```

**Comment by tumashu** [comment]
I think your solution is better

I have benchmarked `exwm-layout--refresh‘ and the result is 0.03-0.17s/10000 times，it is a fast function

The underline problem is that how to deal with `exwm-layout--refresh‘ run-errors， how to force ignore these errors？

**Comment by ch11ng** [comment]
Hi @tumashu,

The performance of `exwm-layout--refresh` actually depends on the amount of windows managed on the active workspace. So refreshing a workspace can be expensive.

> The underline problem is that how to deal with `exwm-layout--refresh‘ run-errors， how to force ignore these errors？

What are the errors (except the one you mentioned in #12)?

**Comment by tumashu** [comment]
i just say the errors which "may", not real error, post-commont-hook seem to ignore any error.

**Comment by tumashu** [comment]
at the moment i can't find any run error of exwm-layout--refresh
