### ISSUE TITLE
How to set simulation keys to send Control?

### ISSUE THREAD

**Issue by ralt** [ch11ng/exwm#148]
I'd like the following:

```
([?\C-s] . (C-f))
```

But can't seem to find a way to do it.

**Comment by ch11ng** [comment]
It should be `([?\C-s] . ?\C-f)` or `([?\C-s] . (?\C-f))` since <kbd>C-f</kbd> is represented as a character in Elisp rather than a symbol.

**Comment by ralt** [comment]
Awesome! This works perfectly :-)

Maybe this should be added in the example?

**Comment by ralt** [comment]
I added these that could be shown as examples:

```
   ([?\C-y] . (?\C-v))
   ([?\M-w] . (?\C-c))
```

**Comment by ch11ng** [comment]
Many EXWM users use terminal emulators and those keys does not work in such case thus can be confusing.  <kbd>C-k</kbd> is an exception though as I want to show how a key sequence can be defined and how to select text with the <kbd>S</kbd> modifier.  So I will not add those keys to the example and I believe users can just figure it out by themselves.

**Comment by aplaice** [comment]
Sorry for commenting on a closed issue, but, rather embarrassingly, I also had problems with sending control+a letter (in the end I came up with the not very readable method of using the numerical code — `([?\C-x ?h . #x01)` or just 1 for `C-a` to select all etc.), so at least one other user did not figure it out for themselves.

If possible and if it doesn't lead to other problems, I would suggest adding the example of

    ([?\C-x ?h] . ?\C-a)

AFAICT it doesn't steal a keybinding from bash (as one would need to send it with `C-c C-q` anyway) nor from emacs (marking the whole exwm buffer doesn't seem to mean anything).


PS Thanks for creating this highly extensible and surprising stable window manager!

**Comment by ch11ng** [comment]
I'd discourage the use of <kbd>C-x</kbd> in simulation keys as it's so frequently used in Emacs.  But whether using it is totally up to users.  I usually short <kbd>C-c C-q</kbd> into <kbd>C-q</kbd> BTW.

It seems the syntax of key events is a bit cryptic to most of you.  Would it be helpful to create some customization options?

**Comment by aplaice** [comment]
Some customisation options would be great!

It's probably the "fault" of the `kbd` function, which works sufficiently well, that until now, I hadn't been punished for not having understood key events.

Is there any problem in using key chords prefixed with `C-x` that one would otherwise not use in exwm-mode (such as `C-x h`) for simulation? In the case of `C-x h`, I will never use the shadowed `mark-whole-buffer` while in exwm-mode; the shadowing is limited to just the `exwm-mode-map`, so it does not extend to "normal" emacs buffers; and all the other key chords prefixed with `C-x` are still present in the relevant keymaps and seem to work, both in exwm-mode and others. (I may very well be missing some important subtlety.)

Thanks!

**Comment by ch11ng** [comment]
@aplaice,

Because it'd make EXWM intercept all keys prefixed with <kbd>C-x</kbd> in `line-mode`.  Though users won't notice it.

**Comment by aplaice** [comment]
Ah, that makes sense. Thanks again!

**Comment by agzam** [comment]
By the way does anyone know how to use "Super" key? I want something like

            ([?\s-h] . [\C-s-tab])
            ([?\s-l] . [\C-tab])

but that's not working, can't seem to be able to bind to super at all, what am I missing?
