### ISSUE TITLE
Feature request: treat any text input area as an emacs buffer

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#162]
Hello everyone,
The question has been asked on stackexchange (http://emacs.stackexchange.com/questions/18062/edit-any-input-field-in-emacs-buffer). That question hasn't been answered.

The alternative question is how to have the emacs keybinding work everywhere (http://superuser.com/questions/993950/how-do-i-make-emacs-key-bindings-work-everywhere-in-linux). One partial solution is to use openbox. It is quite easy to set C-f to be forward a letter globally in openbox, but in a emacs window that setting has to be disabled, as in evil-mode, C-f is pagedown. Openbox doesn't have a hook to disable the global setting after window switch. Another solution is to use autokey (http://askubuntu.com/questions/245746/emacs-like-keybindings-system-wide), it has hooks, but it doesn't work for some windows.

So will you be interested in solving this problem? 
Thank you in advance.

**Comment by ch11ng** [comment]
I think some behaviors such as `forward-word` and `backward-word` have to be mimicked in a level no lower than toolkit.  IIRC Gtk+ 3 has such functionality.  If you don't need those behaviors then things are much simpler.

I've not checked how openbox and autokey implement that, but it sounds like what they do are quite similar to the implementation in EXWM (which is basically key translation).  I think the implementation in EXWM is superior since 1) EXWM accepts key sequences as inputs and outputs and 2) the translation map can be different for different applications.  One drawback of the current implementation is that it does not work for some (legacy) applications, which can actually be fixed by exploiting the XTEST extension.

And back to your original question, I think it's a totally different approach and it might be possible.  The only problem is how to copy texts from input fields and paste them back.  One can utilize XIM to distinguish among different input fields so changing windows is probably not a problem.

**Comment by QiangF** [comment]
A link for emacs keybinding systemwide:
http://yashiromann.sakura.ne.jp/x11keymacs/index-en.html

**Comment by zevlg** [comment]
JFYI: xwem has some powerful qualification capabilities to find out what kind of X client (or even is X client's context) currently active.  So using this capabilities xwem implements `keytt` minor mode that does keys translation - https://github.com/zevlg/xwem/blob/master/extra/xwem-keytt.el  (X events sending done using XTEST)

I was using this minor mode for 10 years without any inconveniences

**Comment by ch11ng** [comment]
@QiangF, I've just checked the source of x11keymacs.  It seems it also does direct key translation, but at a lower level.  Low level key translation is not necessarily superior than what EXWM currently does in X window; indeed it'd better if we can perform translation at a higher level, for example if the translation is context-aware or even text-aware then we can implement something interesting like `forward-word`.  However I've not tried the tool yet so maybe I missed something.

@zevlg, context-aware key translation is really awesome! How did you implement that? I just quickly gone through the code but could not find it.

**Comment by zevlg** [comment]
@ch11ng xwem-manage.el implements very powerful clients matching functionality - `xwem-cl-match-p`.  And xwem-keytt.el uses this functionality to search proper keymap to use in keys translation (`xwem-keytt-find-keymap`)

So, for example, to use special translation keymap in `gv` application (but not in its dialog boxes) you do

```lisp
(xwem-keytt-add-keymap '(and (application "gv")
                             (not (predicate xwem-cl-transient-for-p)))
                       xwem-keytt-gv-keymap t)
```

where

```lisp
 (and (application "gv")  (not (predicate xwem-cl-transient-for-p)))
```

is client qualifier (matching rule)

xwem's client qualifiers is kind of tiny DSL for matching X clients

**Comment by ch11ng** [comment]
@zevlg, it seems xwem-manage.el uses class and instance names to match X windows.  It can be done in EXWM though not in a very straightforward way.

**Comment by QiangF** [comment]
Following links on x11keymacs, I find several others including xfumble, keyfake and rbindkeys. Only this version of rbindkeys work for me (https://github.com/zw963/linux_key_rebinding). The command is 
rbindkeys /dev/input/event12
However, there doesn't seem to have a input device for a remote X2go session, the program is not usable on a remote computer. 
So maybe implement the key change in a higher level can avoid such issue.

**Comment by ch11ng** [comment]
@QiangF, could you provide a list of functionalities those utilities provides that are missing in EXWM? Some functionalities might not seem possible but we'll try to implement them.

**Comment by QiangF** [comment]
Hi Chris,
I am still using openbox. The list of features I am wishing for is as follows:

1 convert 
KEY_CAPSLOCK to KEY_LEFTCTRL
KEY_COMPOSE to KEY_CAPSLOCK

2 cursor move binding for non emacs widows
bind_key [KEY_LEFTCTRL, KEY_F], KEY_RIGHT
bind_key [KEY_LEFTCTRL, KEY_B], KEY_LEFT
bind_key [KEY_LEFTCTRL, KEY_P], KEY_UP
bind_key [KEY_LEFTCTRL, KEY_N], KEY_DOWN
bind_key [KEY_LEFTCTRL, KEY_A], KEY_HOME
bind_key [KEY_LEFTCTRL, KEY_E], KEY_END

3 word move for non emacs widows
bind_key [KEY_RIGHTALT, KEY_F], [KEY_LEFTCTRL,KEY_RIGHT]
bind_key [KEY_RIGHTALT, KEY_B], [KEY_LEFTCTRL,KEY_LEFT]

4 page scroll for non emacs widows
bind_key [KEY_LEFTCTRL, KEY_V], KEY_PAGEDOWN
bind_key [KEY_LEFTALT, KEY_V], KEY_PAGEUP

5 edit for non emacs widows
bind_key [KEY_LEFTCTRL, KEY_D], KEY_DELETE
bind_key [KEY_LEFTCTRL, KEY_H], KEY_BACKSPACE
bind_key [KEY_LEFTCTRL, KEY_M], KEY_ENTER
bind_key [KEY_LEFTCTRL, KEY_I], KEY_TAB
bind_key [KEY_LEFTCTRL, KEY_LEFTBRACE], KEY_ESC

6 cut, copy and paste for non emacs widows
bind_key [KEY_LEFTCTRL, KEY_W], [KEY_LEFTCTRL,KEY_X]
bind_key [KEY_LEFTALT, KEY_W], [KEY_LEFTCTRL,KEY_C]
bind_key [KEY_LEFTCTRL, KEY_Y], [KEY_LEFTCTRL,KEY_V]

6 kill line for non emacs widows
 bind_key [KEY_LEFTCTRL, KEY_K] do |event, operator|
   # Shift+End : select text to end of line
   operator.press_key KEY_LEFTSHIFT
   operator.press_key KEY_END
   operator.release_key KEY_END
   operator.release_key KEY_LEFTSHIFT

   # Ctrl+x : cut
   operator.press_key KEY_LEFTCTRL
   operator.press_key KEY_X
   operator.release_key KEY_X
   operator.release_key KEY_LEFTCTRL
 end

7 stroke key binds  for non emacs widows
if your input was not hit any bind_key, the input will be ignored
bind_prefix_key [KEY_LEFTCTRL, KEY_X] do

  # C-xk: close tab, etc.
  bind_key KEY_K, [KEY_LEFTCTRL, KEY_W]

  # C-xC-s: save
  bind_key [KEY_LEFTCTRL, KEY_S], [KEY_LEFTCTRL, KEY_S]

  # C-xb: next tab, etc.
  bind_key KEY_B, [KEY_LEFTCTRL, KEY_TAB]

  # C-xC-g: ignore C-x prefix bind
  bind_key [KEY_LEFTCTRL, KEY_G], :ignore

  # C-xC-c: close window
  bind_key [KEY_LEFTCTRL, KEY_C], [KEY_LEFTALT, KEY_F4]
end

8 settings per window class (or title)
Emacs skip all key rebinding
window(:through, :app_class => /Emacs$/)
Firefox I use keysnail so skip all rebinding
window(:through, :app_class => /Firefox$/)
window(:through, :class => /Lxterminal/)

9 bind long press left ctl to escape, add pressed time to the binding of
modifing keys.
xcape can do it locally, but not from a remote desktop

10 window specific scratch buffer that can be switched to or created (if not
already exist) with a shortcut, ie. scratch buffers that remembers the widow it
is created for. Kill that buffer copies its content to the clipboard,
switched to the window and optionally paste its content.

Thank you!

**Comment by ch11ng** [comment]
Hi @QiangF,

> 1 convert 
KEY_CAPSLOCK to KEY_LEFTCTRL
KEY_COMPOSE to KEY_CAPSLOCK

This requires at least the XKB extension, however the XKB module of XELB does not work on Emacs 24 so let's wait until the release of Emacs 25.

> 2 disable emacs global keybinding for emacs, firefox etc.
I am not sure if this can be set in a hook such as exwm-update-title-hook with the function exwm-input-set-simulation-keys

This is easy to implement.  I'll add it shortly.

> 3 bind long press left ctl to escape, add pressed time to the binding of
modifer keys
xcape can do it locally, but not from a remote desktop

Same as the first one, but I'm not sure if I can make it work on a remote desktop.  Also please note that key simulations only work in `line-mode`, and if you start the remote desktop in fullscreen (which is in `char-mode`) the simulations won't work.

> 4 window specific scratch buffer that can be switched to or created (if not
already exist) with a shortcut, ie. scratch buffers that remembers the widow it
is created for. Kill that buffer copies its content to the clipboard (or bind it to a key) switched to the window and optionally paste its content.

I think this requires more considerations.  It seems the buffer is used for editing text of input fields, so does it also copy text from input fields (or clipboard)? Can we simply use minibuffer since it appears less distracting?

**Comment by QiangF** [comment]
Thank you Chris.
I think your thought on 4 (window or input field specific buffer) is better, maybe the minibuffer should enlarge automatically as lines grow, and remembers not yet commintted text for an input field ( people often do multitasks at the same time, they switch application often).

**Comment by akater** [comment]
Something relevant might be going on [in this GitHub repository](https://github.com/zachcurry/emacs-anywhere), as discussed [in this reddit comment](https://www.reddit.com/r/lisp/comments/80vvum/emacs_anywhere_use_emacs_anywhere/duzldby/). 

Whatever it is, it's OS X only for now.

**Comment by QiangF** [comment]
It uses xdotool. We can achieve the same with exwmx-sendstring.
https://github.com/ch11ng/exwm/issues/387
