### ISSUE TITLE
How can I set floating-window‘s init width and height

### ISSUE THREAD

**Issue by tumashu** [ch11ng/exwm#181]
When I  float firefox， its window is too big， I want to resize its window to 80% screen when I toggle float， how to do it？

**Comment by tumashu** [comment]
Another approach it:  how can I limit the floating-window's max width and max height, for example, 80% screen?

**Comment by tjackson** [comment]
Maybe a better way would be to allow floating rules similar to what dwm and its brethren do so that you can respect an app's requested geometry.

**Comment by tumashu** [comment]
ah, this is a good idea...

**Comment by ch11ng** [comment]
EXWM currently does not quite respect normal hints (ICCCM) so an X window might not end up with its optimal size.  And due to the size restriction on Emacs frames, some requested geometries are simply not possible.  Of course these problems have to be resolved in the future.

Using rules is a good idea. I'd appreciate if someone could provide a list of functionalities need to be taken into consideration, or even make a draft implementation.

**Comment by tumashu** [comment]
Maybe we should (setq width (* 0.7 display-width)) and (setq height (* 0.7 display-height)) instead.  
```
...
   (if (> width display-width)
          ;; Too wide
          (progn (setq x 0
                       width display-width))
        ;; Invalid width
        (when (= 0 width) (setq width (/ display-width 2)))
        ;; Make sure at least half of the window is visible
        (when (or (> (+ x (/ width 2)) display-width) (> 0 (+ x (/ width 2))))
          (setq x (/ (- display-width width) 2))))
      (if (> height display-height)
          ;; Too tall
          (setq y 0
height display-height)

...
```

**Comment by tumashu** [comment]
Maybe we can add a variable, which let user use their own rule-method, for example: `exwm-floating-rules-function'

**Comment by ch11ng** [comment]
It's now possible with `exwm-manage-configurations`.
