### ISSUE TITLE
Question: how to set a global key binding to toggle exwm line mode and char mode

### ISSUE THREAD

**Issue by QiangF** [ch11ng/exwm#188]
Hello everyone,
To do that, I need a function to tell which mode the current exwm is in. Also, why not set the default mode to exwm char mode, and let exwm-reset reset to char mode, as most of the emacs keybindings do not work in other applications.
Thank you for your help!

**Comment by ch11ng** [comment]
> I need a function to tell which mode the current exwm is in.

There's a private buffer-local variable recording this status, but I'm not sure if it should be made public (see below).

> Also, why not set the default mode to exwm char mode, and let exwm-reset reset to char mode, as most of the emacs keybindings do not work in other applications.

Because no Emacs command is accessible in `char-mode` except those globally bound, while `line-mode` works with most types of applications (where <kbd>C-x</kbd> and <kbd>C-c</kbd> are not frequently used) without ever being switched to `char-mode`.  Besides `line-mode` is essential for mode-specific keys and simulation keys.  `char-mode` is usually used temporarily I suppose.  Emacs should be treated as the first-class citizen, at least not subordinate to other applications, and this design (`line-mode` as the default) is in accordance with this principle.

`exwm-reset` actually does more than switching back to `line-mode`, for instance it also exits fullscreen mode (note fullscreen X windows are in `char-mode`) and it may gain more functionalities in the future.  One should always use this to switch to `line-mode` to avoid the situation where a fullscreen X window is working in `line-mode`.  For this reason I'd rather provide a "toggle" command directly instead of exposing that variable.  Are there any other use cases for this variable?

**Comment by QiangF** [comment]
@ch11ng   a toggle command would be perfect fit. There is no need to expose that variable.
Thank you!

**Comment by ch11ng** [comment]
I've added `exwm-input-toggle-keyboard` command for this.

**Comment by QiangF** [comment]
But I tried both the following and neither works. 

    (setq exwm-input--simulation-keys
       '(([134217736] . C-prior)))

    (setq exwm-input--simulation-keys
       '(("C-M-h" . C-prior)))
