### ISSUE TITLE
Active mode-line

### ISSUE THREAD

**Issue by jtamagnan** [ch11ng/exwm#203]
When a buffer is selected the mode-line usually changes to be a different color to indicate that that buffer is selected. This doesn't seem to always happen when using exwm. I'm not sure exactly which actions cause it but it happens very often enough.

**Comment by ch11ng** [comment]
I don't think I've ever run into this problem.  Was the buffer successfully switched? Could you try with the minimal setup and see if you can reproduce it?

**Comment by jtamagnan** [comment]
I found out that it was an incompatibility issue with powerline. I found that `(remove-hook 'focus-out-hook 'powerline-unset-selected-window)` fixes the issue. This works for me. If I find a better solution later on I'll update. Thanks

**Comment by Stebalien** [comment]
As far as I can tell, this is a bug (maybe unfixable?). Focusing an X window appears to trigger the `focus-out-hook` because the emacs frame gets unfocused (at the Xorg level). Really, these events should only be triggered when focusing a new frame. You may be able to fix this by nooping out `handle-focus-out` and `handle-focus-in` (see `frame.el`) and firing these events yourself.

**Comment by ch11ng** [comment]
Even if the frame gets unfocused the mode-line is still considered active by Emacs.

**Comment by Stebalien** [comment]
Powerline visually "dims" the modeline when the frame gets unfocused to make it clear that input won't go to that window.

The problem here is that, even though the frame is logically focused (from the user's perspective), emacs doesn't consider it focused because the frame's X window itself isn't focused. That's why I suggested messing with the frame focus internals to make emacs think the frame retains focus when one of its X windows is focused. For the purposes of input, it does.

**Comment by ch11ng** [comment]
It's a design decision made to powerline and there's really nothing can be done here.  In X11 there's only one X window that has the focus at any time.

**Comment by Stebalien** [comment]
>  In X11 there's only one X window that has the focus at any time.

I'm talking about frames, not X windows. Emacs usually considers the frame
focused if and only if the frame's X window has focus. However, this isn't
correct under EXWM because frames can "contain" (conceptually at least) X
windows.

This isn't powerline specific; anything trying to track input focus will get
very confused. It turns out this is causing #222.

> really nothing can be done here.

Again, can't you just override the `handle-focus-in` and `handle-focus-out` and
manually call the focus hooks when relevant (when you actually switch logical
frames)?

**Comment by ch11ng** [comment]
It actually makes some sense to run `focus-in-hook` and `focus-out-hook` manually.  I've made the change in 52dc2616240d43b8c15e10edfdd34b1e0039a10f`.

**Comment by Stebalien** [comment]
Thanks! Works like a charm.
