### ISSUE TITLE
Fullscreen programs do not allow interception of commands

### ISSUE THREAD

**Issue by Myrl** [ch11ng/exwm#207]
I have a feeling that this is intentional. Is there a way to fullscreen a program and still allow interception of commands?

**Comment by ch11ng** [comment]
Yes, this is intentional.  One solution would be to make a workspace display only one window and hide the mode-line (of course you should hide the minibuffer).

**Comment by jtamagnan** [comment]
Would it be possible to simply add a variable to toggle. The last line in `exwm-layout-set-fullscreen`? That way `(call-interactively #'exwm-input-release-keyboard)` doesn't get called?

**Comment by ch11ng** [comment]
Many `line-mode` keys interact with Emacs so they won't work correctly with Emacs frames invisible if they are intercepted.  We'd like to know which keys/commands you want to make use of in fullscreen mode.  BTW what's wrong with the solution I proposed in the previous comment? It can make X windows visually fullscreen and should make much more sense I think.

**Comment by taohansen** [comment]
>  One solution would be to make a workspace display only one window and hide the mode-line (of course you should hide the minibuffer).

could you provide an elisp example of this solution?

**Comment by ch11ng** [comment]
First you should start Emacs with

```elisp
(setq exwm-workspace-minibuffer-position 'bottom)
```

Then after starting your application you need to hide the mode-line with <kbd>M-x exwm-layout-hide-mode-line</kbd>.

**Comment by ch11ng** [comment]
I believe the solution I provided meets your requirement.  So I'm closing this issue now.

**Comment by port19x** [comment]
I had severe problems with this as well when trying to play games on a two monitor system with different resolutions for each.
My 4k monitor would still play the game at 1080p, with lots of black area and game freezes.
Disabling the 1080p monitor (since it's the closed laptops screen anyway) resolved that issue.
`xrandr --output eDP --off`
The message area and modeline still show by default, but `C-c C-f` works as expected to get true full screen
