### ISSUE TITLE
switching buffers in a split window changes window-layout

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#21]
1. Split the initial scratch buffer window vertically
2. Open a file in the first window.
3. Open another file in the second window.
4. Now, switching to scratch buffer in one window changes the layout to single-window configuration.

This behavior is not limited to just scratch buffer, it can be reproduced with file buffers also.

**Comment by ch11ng** [comment]
So I suppose you enabled `ido-mode` or something similar. This is actually a feature of `ido-mode` that when you tell it to switch to a buffer, it tries to switch a frame instead if the buffer is present on that frame. Of course for EXWM this is a bug.

Previously, I solved this problem by hiding all other workspaces and it worked well. But since the introduction of RandR support (@86764d2), workspaces can no longer be hidden. I'm still seeking a solution.

**Comment by ch11ng** [comment]
Hi @bvk,
I've provide a workaround for `ido-mode`, as shown in the [configuration example](https://github.com/ch11ng/exwm/wiki/Configuration-example).
