### ISSUE TITLE
minibuffer question locks up exwm on GUI applications + pdf-tools

### ISSUE THREAD

**Issue by map7** [ch11ng/exwm#218]
I'm using exwm 0.12 and pdf-tools 20161207 and I have noticed a bug in which I cannot answer a question in the minibuffer 'File <pdf> is large, really open?' this only happens with the buffer in focus is a GUI application (in my case it was pavucontrol or google-chrome). If it's a normal emacs buffer in focus I can answer the question and continue on.

When the bug happens I cannot do anything as emacs is waiting on an answer which I cannot get focus to and answer. I have to quit the GUI application and then I can answer and continue working.

**Comment by ch11ng** [comment]
Sorry for the late reply.  It's likely pdf-tools was not involved in the problem since the message was from Emacs itself.  However I could not reproduce the problem with the following steps: a) open a GUI application (Chromium for example), b) press <kbd>C-x C-f</kbd> (`ido-find-file`) to open a large file (also tried a large PDF file with pdf-tools installed) and c) try to answer the question.  I could answer the question each time.

And according to your description the input focus was not on the minibuffer but was it on the GUI application?

**Comment by map7** [comment]
After trying again this time with the gedit GUI application open when I go through ido and open up a large pdf it asks the question, I answer 'y' and it asks the question again saying 'Please answer with y or n' and I try answering with 'y' again but it doesn't open the pdf. I exit the gedit application and then I can hit 'y' and then it opens up the pdf. Whilst I was hitting 'y' there was no text being printed into the gedit application so I would now say that the focus is still on the minibuffer but when I hit 'y' it is not sending 'y' to the minibuffer until I close the GUI application.

I'm using emacs 26.0.50.4 (compiled from github master branch 17th Jan). It could be because I'm using the latest emacs version from github. I'll close this as I think it maybe due to me using the latest emacs.
