### ISSUE TITLE
Maintaining the leader key-binding in EXWM

### ISSUE THREAD

**Issue by paralin** [ch11ng/exwm#268]
I use spacemacs, and am a bit new to emacs in general. I've read through the exwm docs and even the code itself and haven't found a way to do this.

I have bound my spacemacs leader key to `s-SPC` (super-space). How can I make this keybinding remain when working in exwm windows?

**Comment by ch11ng** [comment]
IIRC someone once gave a solution.  Basically you need to modify `exwm-input-prefix-keys` so that Emacs would receive that key.

**Comment by akirakyle** [comment]
I suggest you use the exwm layer here: https://github.com/syl20bnr/spacemacs/pull/3321
The relevant bindings are all in `packages.el`
By default the layer binds `s-SPC` to `spacemacs/exwm-app-launcher` but you can change that to something else (I use `s-m`) then you need to add `(push ?\s-\  exwm-input-prefix-keys)` so that `s-SPC` is passed to emacs in `EXWM` buffers then in my `.spacemacs` I set `dotspacemacs-emacs-leader-key "s-SPC"` so that I can keep `SPC` as my usual leader key in emacs buffers as well as having `s-SPC` as my leader in `EXWM` buffers

**Comment by medranocalvo** [comment]
@paralin Please try the Spacemacs' instructions in the wiki: https://github.com/ch11ng/exwm/wiki/Notes-to-Spacemacs-users.  Any improvements to the wiki are appreciated.

Please reopen if you still find difficulties.
