### ISSUE TITLE
active window marker

### ISSUE THREAD

**Issue by zabbal** [ch11ng/exwm#3]
Would be great to have (configurable) visual clue regarding which window is active right now - something like 1-pixel red line around buffer which currently have focus would be perfect.

**Comment by ch11ng** [comment]
Here are some possible workarounds:
+ Depending on the color-theme you choose, you may be able to pick the active buffer by its mode-line.
+ Carefully set the width/height and color of e.g. fringes, and update them in `buffer-list-update-hook`. Not sure if it works though.

The least preferable way is to set the border of a window with `xcb:ConfigureWindow` request, since the input focus / active buffer changes frequently.

**Comment by ch11ng** [comment]
I'm closing this issue now. Please reopen it if you have good reason to implement such feature.
