### ISSUE TITLE
Polybar tray support

### ISSUE THREAD

**Issue by fm4d** [ch11ng/exwm#328]
Hello,

Polybar seems to be working very well with EXWM and it has built-in tray which seems reliable and bugfree. Unfortunately the tray dissapears after switching workspaces. I've searched for solution within Polybar issues but found nothing. Hopefully this should not be hard to debug and fix and we would have another great bar for EXWM.

**Comment by ch11ng** [comment]
Polybar implements systemtray as a separate X window ("tray") aside from the "bar" itself.  The "tray" has no struts set so it's not managed by EXWM.  On switching workspaces EXWM would raise docks (X windows with struts set) so the "bar" would be raised but not the "tray".  However the "bar" is longer than it should be and it obscures the "tray" (or one could claim that EXWM should raise the "tray" as well but it's not managed by EXWM, besides the order also matters).  In EXWM we always raise X windows so it seems quite nature to raise the "bar".  I noticed polybar is quite configurable so can this be fixed by make a change to its configuration?

**Comment by medranocalvo** [comment]
It seems to me there's nothing EXWM can do here.  Please, reopen if that's not the case.
