### ISSUE TITLE
exwm-input-set-key for new bindings require a restart to work in EXWM buffers

### ISSUE THREAD

**Issue by Ambrevar** [ch11ng/exwm#361]
With EXWM running and `s-p` is unbound, if I evaluate

    (exwm-input-set-key (kbd "s-p") #'helm-pass)

the new binding works in Emacs buffers but not in EXWM buffers.
A restart fixes it.

Is it to be expected or is it a bug?
If the former, then we should document it in the function docstring and in the wiki.

**Comment by ch11ng** [comment]
Key bindings set by calling `exwm-input-set-key` as a function do not immediately take effect.  It's the expected behavior as we use it in configuration.  However if you run `exwm-input-set-key` as a command (by invoking <kbd>M-x exwm-input-set-key</kbd> for example) then the key binding would take effect set right away.

**Comment by Ambrevar** [comment]
I see that from the function definition.  Would you mind mentioning this
in the docstring?  That'd be great, thanks!

**Comment by ch11ng** [comment]
Fine.
