### ISSUE TITLE
wxWidgets TextCtrl edit attempt causes freeze

### ISSUE THREAD

**Issue by rayslava** [ch11ng/exwm#430]
Sample app (reduced testcase from KiCAD):
```python
#!/usr/bin/python
# -*- coding: utf-8 -*-
import wx

class Frame(wx.Frame):
    def __init__(self, title):
        wx.Frame.__init__(self, None, title=title, pos=(150,150), size=(350,200))
        panel = wx.Panel(self)
        box = wx.BoxSizer(wx.VERTICAL)
        m_edit = wx.TextCtrl(panel, value="test", size=(300, 20))
        box.Add(m_edit, 0, wx.ALL, 10)
        panel.SetSizer(box)
        panel.Layout()

app = wx.App(redirect=True)
top = Frame("<<test>>")
top.Show()
app.MainLoop()
```
Steps to reproduce freeze
- Type some text in the `TextCtrl`
- Try to use backspace or left arrow key inside
- Whole Emacs GUI freezes

Sometimes it can unfreeze in a minute, sometimes I have to kill it from VT.
Reproduceable on Emacs 25 and Emacs 26.

**Comment by ch11ng** [comment]
It turns out there's a [bug](http://trac.wxwidgets.org/ticket/16840) in wxWidget with XIM.  Perhaps you have enabled [EXIM](https://github.com/ch11ng/exim/) which is an IME implementing XIM.  After a bit of research I find out a wxWidget app would keep sending cursor keys / backspace to EXIM even though EXIM forwards those events back with the synchronous flag set.  And the events flooding in would stave EXWM and freeze Emacs.  There's no such problem with native GTK apps.

**Comment by rayslava** [comment]
Yes, I do use EXIM, it's very convenient.
Okay, so I have to wait until 3-year-old bug to be fixed? :(

However I'll try to change envvar and try to run wxWidgets apps without EXIM.

**Comment by ch11ng** [comment]
Or you can turn to other IMEs not relying on XIM.

**Comment by ch11ng** [comment]
@rayslava This is a wxWidget bug and nothing can be done here.  So I'm closing it.
