### ISSUE TITLE
Getting/Setting Window Properties

### ISSUE THREAD

**Issue by pjones** [ch11ng/exwm#439]
Is there a function in EXWM for getting and setting window properties?  Right now I'm shelling out to xprop and that feels pretty ugly.

Digging through the EXWM code it seems like I would need access to the `exwm-connection` value so I can call into XELB.  Is that correct?

Thanks!

**Comment by ch11ng** [comment]
Getting and changing properties can be done with `xcb:GetProperty` and `xcb:ChangeProperty` requests.  We don't directly use them in EXWM usually (with the only exception being `exwm-input--update-timestamp`), because most standard properties defined in ICCCM and EWMH already have wrappers for manipulating them (see xelb/xcb-icccm.el and xelb/xcb-ewmh.el).  Also it's recommended to create a new connection rather than reusing the builtin one:

``` elisp
(let ((conn (xcb:connect)))
  (...)
  (xcb:disconnect conn))
```

**Comment by pjones** [comment]
Perfect.  Thank you.
