### ISSUE TITLE
Block cursor turns into filled-rectangle and lined-rectangle for every key press

### ISSUE THREAD

**Issue by bvk** [ch11ng/exwm#44]
I use emacs with black colored block cursor in non-blinking mode.  When Emacs loses focus, cursor usually turns from filled-rectangle shape to lined-rectangle (i.e., area of the cursor is white and all four edges of the cursor are black).

When exwm starts, cursor behaves just fine, but after some use (I mostly use urxvt terminal in a vertically-split window with screen running inside and google-chrome in another workspace) I notice that block-cursor turns into lined-rectangle and back into filled-rectangle for every key press.

It seems key-pressed event turns it into lined-rectangle and key-released event turns it back into filled-rectangle.

**Comment by ch11ng** [comment]
I believe this issue only occurs when you have mouse over an X window while trying to type something in Emacs. This is because KeyPress events are generated on an X window when we have keys grabbed on it and mouse over it. The input focus is temporarily lost at that moment. I don't have a better solution for this issue yet. Any ideas are welcomed.

**Comment by ch11ng** [comment]
Fixed in c75a8b82ec2747a6fe7fc4b3a0dfaf1adca7ea64.
