### ISSUE TITLE
Is there a way to have a workspace mirror another?

### ISSUE THREAD

**Issue by prosoitos** [ch11ng/exwm#445]
I have the same problem as [this unresolved question](https://emacs.stackexchange.com/questions/39041/exwm-mirror-display-of-work-space-1-only-to-second-monitor-work-space-2-not-m). Since I don't think that `randr` allows to do what this person wishes (have one monitor mirror one workspace only, even if another workspace is selected), I thought that a workaround may be to have a workspace mirror a 2nd workspace (if there is a way to achieve that within `exwm`).

For instance:

- Monitor 1: my laptop screen that only I can see
- Monitor 2: display monitor that my students can see

I would like to be able to switch, on monitor 1 (laptop), between what they see and other things without interfering with what they see on the display screen (monitor 2).

If `randr` and/or `exwm-randr` do not allow to do this, then this may be a solution:

- Worspace 1: what I want my students to see all of the time
- Workspace 2: mirror of workspace 1
- Any other workspace: whatever other thing I need to look at

Then I would just have to set `randr` to have:

- Workspace 1 on monitor 2
- any other other workspace (workspace 2 + all the other ones) on monitor 1

I would never switch to workspace 1, considering it as a "display workspace" only. When I would need to see what my students are looking at, I would switch to workspace 2 (so, on my laptop) instead. And when needing to see something else, I would switch to whatever other workspace without interfering with the display monitor.

I hope this makes sense... if you have any hint on how to achieve this (or a direct solution to the problem with `randr` or otherwise), I would sincerely appreciate your help and time!

Thank you.

**Comment by pjones** [comment]
I don't think there's a way to do this with X.  At least I haven't found a way to do it yet and I've been looking for a few years for the same reason you are.

What I do right now is use x11vnc to create a VNC server for the monitor/projector that my students can see.  Then I use ssvncviewer to display that monitor on my laptop's screen.  There's some lag due to all the memory/GPU copying going on but most of the time it works well enough.

**Comment by prosoitos** [comment]
Thank you for your reply. I was hoping this would be achievable with an `exwm` function...

**Comment by prosoitos** [comment]
OK. Thank you for your reply.

It is more a setup that I would like to achieve than a way to show presentations because what I might want to display can vary from a webbrowser to a pdf to a ppt to a CLI, etc.

**Comment by prosoitos** [comment]
> What I do right now is use x11vnc to create a VNC server for the monitor/projector that my students can see. Then I use ssvncviewer to display that monitor on my laptop's screen. There's some lag due to all the memory/GPU copying going on but most of the time it works well enough.

I will give this a try as indeed, it doesn't seem that there is any other solution. Thank you for your suggestion!

**Comment by prosoitos** [comment]
Oh, except that I hadn't realized that I had to create a server for the projector. So this won't work because I use different projectors all the time while giving workshops, conferences, etc. :slightly_frowning_face:

**Comment by pjones** [comment]
@prosoitos What do you mean?

I also connect to many different projectors and this system *mostly* works for me.  After connecting to the projector I run a script that starts x11vnc and ssvncviewer:

```sh
x11vnc -clip xinerama1 -viewonly \
       -once -localhost -quiet \
       -cursor_drag -cursorpos \
       -noxdamage \
       -ncache 12 -nonc \
       -q  2> /dev/null &

sleep 2
ssvncviewer localhost
wait
```

So I get a VNC viewer on my laptop screen showing me what's on the projector's screen.  The only issue I have with this setup is that sometimes VNC becomes unresponsive for about 30 seconds.  This happens when nothing has been changing on the projector's screen for awhile.  I still need to figure out how to turn off all settings that are meant to improve network performance since the server and client are on the same machine.

**Comment by prosoitos** [comment]
Oh, I see. Thanks for the additional info. I think the problem is my lack of experience with remote access. I will give this a try.

Thank you for taking the time to help! I appreciate.

**Comment by medranocalvo** [comment]
This seems resolved.  Please reopen if that's not the case.

**Comment by prosoitos** [comment]
Sounds good. It would be really neat is X would allow for this in the future though. But that is not up to exwm.
