### ISSUE TITLE
Hooks only get removed on successful `exwm-init`.

### ISSUE THREAD

**Issue by jaccarmac** [ch11ng/exwm#472]
Discovered this while curating some hooks. Low-priority issue but noticed a discrepancy with my Windows setup again. The branch ending in `(message "[EXWM] Not running under X environment")` (and some other branches, but that's the one I noticed) doesn't clean up hooks, so `exwm-init` continues to get run on every frame create afterwards. On Windows there doesn't seem to be any effect beyond a little message buffer spam.

**Comment by ch11ng** [comment]
The reason is the first EXWM workspace might not among the first few frames created after Emacs starts.  For example one may launches a Emacs daemon and start an EXWM session afterwards with emacsclient.  So instead of removing the hook one may selectively enable EXWM depending on the value of `system-type`:

```elisp
(when (memq system-type '(berkeley-unix gnu gnu/linux))
  (exwm-enable))
```
