### ISSUE TITLE
kill-buffer-and-window (C-x 4 0) doesn't work as expected

### ISSUE THREAD

**Issue by Vifon** [ch11ng/exwm#510]
`kill-buffer-and-window` (<kbd>C-x 4 0</kbd>) in buffers running exwm-mode doesn't delete the Emacs window, it only kills the buffer / X window, essentially working just like `kill-buffer` (<kbd>C-x k</kbd>) but without a prompt.

**Comment by ch11ng** [comment]
Hi, this is because EXWM buffers cannot be killed directly but instead `exwm-manage--kill-buffer-query-function` is called to notify the corresponding X windows to gracefully destroy themselves.  There is no way here for EXWM to detect if a window is intended to be killed but it's viable to revise `kill-buffer-and-window` as follows (or modify the key binding instead; note the hook is not removed when compared with the original definition):

```elisp
(defun kill-buffer-and-window ()
  "Kill the current buffer and delete the selected window."
  (interactive)
  (let ((window-to-delete (selected-window))
	(buffer-to-kill (current-buffer))
	(delete-window-hook (lambda () (ignore-errors (delete-window)))))
    (unwind-protect
	(progn
	  (add-hook 'kill-buffer-hook delete-window-hook t t)
	  (if (kill-buffer (current-buffer))
	      ;; If `delete-window' failed before, we rerun it to regenerate
	      ;; the error so it can be seen in the echo area.
	      (when (eq (selected-window) window-to-delete)
		(delete-window)))))))
```

**Comment by Vifon** [comment]
Your explanation makes sense, thank you!

This function seems to be working very well. I'll just patch it with el-patch in my EXWM initialization. Should I expect any complications apart from buffers lingering around even though they didn't succeed in actually getting killed? (and that should be very rare)

**Comment by ch11ng** [comment]
Glad it works!

> Should I expect any complications apart from buffers lingering around even though they didn't succeed in actually getting killed? (and that should be very rare)

I'm not sure TBH.  I didn't foresee this problem after all.
