### ISSUE TITLE
Can't Kill Buffer With Dynamic Title

### ISSUE THREAD

**Issue by B2RN** [ch11ng/exwm#600]
Minor issue but certain buffers, like remote consoles for servers, include dynamic content like FPS information, in the title.

Since the FPS information changes, trying to kill those results in:

`funcall-interactively: No buffer named ...`

**Comment by ch11ng** [comment]
There seem to be no code killing a buffer by specifying its name.  Could you please capture a backtrace with `(setq debug-on-error t)` (it's fine to edit out sensitive info).

**Comment by medranocalvo** [comment]
That's probably due to `kill-buffer`'s interactive spec, which lets you select a buffer by its name.   The name changes between the moment the completion list is built.

I suggest you use `kill-this-buffer` for this precise buffer instead, or that you override the window title via `exwm-update-title-hook` (see the configuration example https://github.com/ch11ng/exwm/wiki/Configuration-Example).

**Comment by B2RN** [comment]
> That's probably due to `kill-buffer`'s interactive spec, which lets you select a buffer by its name. The name changes between the moment the completion list is built.
> 
> I suggest you use `kill-this-buffer` for this precise buffer instead, or that you override the window title via `exwm-update-title-hook` (see the configuration example https://github.com/ch11ng/exwm/wiki/Configuration-Example).

Using `kill-this-buffer` worked just fine. Much obliged for the tip. @ch11ng Do you still want that backtrace before I close the issue?

**Comment by medranocalvo** [comment]
Happy it helped.

**Comment by ch11ng** [comment]
> Do you still want that backtrace before I close the issue?

Not any more.  Thank you, @medranocalvo !
