### ISSUE TITLE
Android Emulator window: grey empty area is flickering

### ISSUE THREAD

**Issue by Comevius** [ch11ng/exwm#620]
The grey empty area of the main Android Emulator window flickers (between white and grey). Does not happen when the mouse interacts with it.

Not sure yet if this is an exwm issue, but it happens with both Android Emulator versions that I tested (release and canary), no matter which graphics acceleration I use.

Only tested with exwm 0.22 (the latest release), but will edit this when I test with master.

**Comment by ch11ng** [comment]
I find Android Emulator keeps trying to resize itself to a predefined size while we make it tiling.  The problem is it declares itself as a normal window with a minimum size but without a maximum size, so we consider it able to work in tiling mode.  It turns out it only works in floating mode (select that window and press <kbd>C-c C-t C-f</kbd>).  You can force it being created in floating mode with the following configuration.

```elisp
(setq exwm-manage-configurations '(((string-match-p "^ ?Android Emulator -" exwm-title)
                                    floating t)))
```

**Comment by medranocalvo** [comment]
@Comevius: please try the suggestion. If it works for you, please add it to the Wiki: https://github.com/ch11ng/exwm/wiki/EXWM-User-Guide#known-issues.

**Comment by Comevius** [comment]
Thanks. It indeed only works in floating mode correctly. I added it to the known issues.
