### ISSUE TITLE
Named workspaces / workspaces in a bar

### ISSUE THREAD

**Issue by minikN** [ch11ng/exwm#716]
Hello,

first of all, if this question has been answered before - sorry for reposting. I've read the user manual as well as searched the issues. I'm interested in using EXWM, however I have two questions:

1. Can workspaces be renamed from `1` to lets say `Browser` or `code`?
2. Can I display the workspaces / currently focused workspace / switch workspace using an external bar like `polybar`? I've seen that there has been some discussion going on about implementing a panel in EXWM itself. I'm fine with using something like polybar. But I would like to know if there is a possibility to display workspace indicators on it?

Looking through polybars config, there is the [xworkspaces](https://github.com/polybar/polybar/wiki/Module:-xworkspaces) module. Which should work with every EWMH compliant WM. 

Cheers.

**Comment by daviwil** [comment]
Hey @minikN, I'll let @ch11ng comment on whether EXWM supports this natively (I don't think it does).  However, I can share how I show the EXWM workspace in Polybar: using `emacsclient` and hooks with Polybar's [`ipc` module](https://github.com/polybar/polybar/wiki/Module:-ipc).

The first step is to define a function in your Emacs configuration that can be invoked via `emacsclient`.  Here's mine:

```
(defun dw/polybar-exwm-workspace ()
  (pcase exwm-workspace-current-index
    (0 "")
    (1 "")
    (2 "")
    (3 "")
    (4 "")))
```
Note that this only uses an icon as a string, but your function could write out the whole list of workspaces and highlight the current workspace index using Polybar's [format tags](https://github.com/polybar/polybar/wiki/Formatting#format-tags).

You'll also need a function that can invoke `polybar-msg` so that you can send an IPC message to your bar when `exwm-workspace-switch-hook` is invoked:

```
(defun dw/send-polybar-hook (name number)
  (start-process-shell-command "polybar-msg" nil (format "polybar-msg hook %s %s" name number)))

(defun dw/update-polybar-exwm ()
  (dw/send-polybar-hook "exwm" 1))

(add-hook 'exwm-workspace-switch-hook #'dw/update-polybar-exwm)
```

Now in your Polybar configuration, define an `ipc` block like so (make sure to name it the same thing that you pass as first parameter to `dw/send-polybar-hook`):

```
[module/exwm]
type = custom/ipc
hook-0 = emacsclient -e "(dw/polybar-exwm-workspace)" | sed -e 's/^"//' -e 's/"$//'
initial = 1
```

Here I'm invoking the function I defined via `emacsclient` and then I run it through `sed` to remove the quotation marks that `emacsclient` wraps the output with.  You'll also need to make sure your bar definition has `enable-ipc` turned on:

```
[bar/whatever-you-call-your-bar]
...
enable-ipc = true
...
```

I do a few more things with Polybar and `emacsclient` like show active `tracking.el` buffers and show a mail icon with my `mu4e` unread message account, so check out my [Desktop.org](https://github.com/daviwil/dotfiles/blob/master/Desktop.org#panel) config file if you're interested.

Hope that helps!

**Comment by sarg** [comment]
Actually exwm has some EWMH support. You just need to set _NET_DESKTOP_NAMES. Here is how to do it:
```elisp
(defvar exwm-workspace-names
  '((1 . "code")
    (2 . "brow")
    (3 . "extr")
    (4 . "slac")
    (5 . "lisp")))

(defun exwm-workspace--ewmh-desktop-names ()
  (mapcar (lambda (el)
            (or (alist-get el exwm-workspace-names)
                (number-to-string el)))
          (number-sequence 1 (exwm-workspace--count))))

(defun exwm-workspace--update-ewmh-desktop-names ()
  (xcb:+request exwm--connection
      (make-instance 'xcb:ewmh:set-_NET_DESKTOP_NAMES
                     :window exwm--root :data
                     (s-join "\0" (exwm-workspace--ewmh-desktop-names)))))

(advice-add 'exwm-workspace--update-ewmh-props
            :before #'exwm-workspace--update-ewmh-desktop-names)
```

**Comment by ch11ng** [comment]
@minikN The `_NET_DESKTOP_NAMES` property is not managed by the window manager but can be set by anyone.
So you probably want preset it manually with utilities like xprop in .xinitrc.
@sarg's method works the same way in case you prefer an Elisp solution.
However the limitation of the above methods is that only UTF-8 characters are allowed so you may want @daviwil's method to display other stuffs.

**Comment by minikN** [comment]
Thank you for the support. I haven't had time to test this. But for the sake of keeping the issue tracker clean I will close this. If I have any troubles setting this up later I will come back here again.

Thanks.

**Comment by minikN** [comment]
I have tried @daviwil method and it works.

However there is one thing I dont get about EXWM, maybe @ch11ng can help:

Im using just vanilla emacs with the default config given. If I do `M-&` and type firefox it opens firefox in the current window. All good. If I do `M-&` again however with another application, it opens it in the same buffer fullscreen, overlaying firefox.

If I want it to open in a new window I have to create one first and then do `M-&` again. Wouldnt I want it to open the application in a new window automatically?

I did not create a new issue for this because I think its just me misunderstanding EXWM.

**Comment by ch11ng** [comment]
@minikN That's by design.  EXWM always displays a new X window in the selected Emacs window, unless it's not able to.  The tiling layout is manually managed by the user.

Perhaps you meant the `*Async Shell Command*` buffer created after each time <kbd>M-&</kbd> is invoked.  We have <kbd>s-&</kbd> as a replacement in the default config.

**Comment by minikN** [comment]
@ch11ng Thank you for clarifying.
@daviwil I'm using your solution for displaying the workspaces.
Allow me two questions:
1. Do you have a solution for displaying the active buffer's name in polybar? I've hacked one together, however it doesn't work for xwindows.
2. Do you color your polybar through emacs or by itself? I'd like to do it through emacs, only thing I could think of are env vars.

**Comment by daviwil** [comment]
For displaying the buffer name you could just expose another Emacs function through an IPC module and `emacsclient` which calls `(buffer-name (current-buffer))` and then use some of the tips in [this StackOverflow question](https://stackoverflow.com/questions/47456134/emacs-lisp-hooks-for-detecting-change-of-active-buffer) to figure out when the buffer changes so that you can use `dw/send-polybar-hook` to notify Polybar to update the module.

I color Polybar using its own configuration, but I did come up with a way to translate Emacs text faces to Polybar formatting strings, see this function:

``` emacs-lisp
(defun dw/propertized-to-polybar (buffer-name)
  (if-let* ((text (substring-no-properties buffer-name))
            (fg-face (get-text-property 0 'face buffer-name))
            (fg-color (face-attribute fg-face :foreground)))
    (format "%%{F%s}%s%%{F-}" fg-color text)
    text))
```

**Comment by SylvianHemus** [comment]
Don't understand or care about using polybar but this variable exists in exwm which points to functionality of this kind being implemented

exwm-workspace-index-map

exwm-workspace-index-map is a variable defined in ‘exwm-workspace.el’.

Its value is ‘number-to-string’

Function for mapping a workspace index to a string for display.

By default ‘number-to-string’ is applied which yields 0 1 2 ... .

  This variable may be risky if used as a file-local variable.
  You can customize this variable.
