### ISSUE TITLE
Pushing <escape> into exwm-input-prefix-keys does not work as expected

### ISSUE THREAD

**Issue by adithyaov** [ch11ng/exwm#791]
```
(define-key key-translation-map (kbd "<escape>") (kbd "C-c"))
(push (kbd "<escape>") exwm-input-prefix-keys)
(exwm-enable)
```

Given the code above,
Pressing `escape` while on a exwm buffer.

**Expected behaviour:**
- Intercepted by emacs.
- Translated to `C-c`
- I can continue typing the suffix which will execute some emacs command.

**Actual behaviour:**
- It sends escape to the program running.

**Comment by Zik42** [comment]
@adithyaov try to do (cl-pushnew (aref (kbd "M-3") 0) exwm-input-prefix-keys)

**Comment by adithyaov** [comment]
@Zik42 Thank you for replying, but that does not work either. I am intrigued though, could you please explain your reasoning behind `(cl-pushnew (aref (kbd "M-3") 0) exwm-input-prefix-keys)` over `(push (kbd "<escape>") exwm-input-prefix-keys)`

**Comment by lucasgruss** [comment]
Hi,
In order to catch escape (to be used with exwm-firefox-evil) I use `(push (aref (kbd "<escape>") 0) exwm-input-prefix-keys)`, which is slightly different than `(push (kbd "<escape>") exwm-input-prefix-keys)`. I am not too sure why it's necessary to be honest, I believe it might have to do with EXWM's inner workings.
It works for me ! 

Another way that should work is mentioned in the readme of [exwm-firefox-evil](https://github.com/walseb/exwm-firefox-evil) (which needs to catch escape):
```
(dolist (k `(
	     escape
	     ))
  (cl-pushnew k exwm-input-prefix-keys))
```

**Comment by adithyaov** [comment]
`(push (aref (kbd "<escape>") 0) exwm-input-prefix-keys)`

@lucasgruss  Works like a charm!

**Comment by Zik42** [comment]
@adithyaov I told  u same anser)
