### ISSUE TITLE
Is there a "Full-frame" mode?

### ISSUE THREAD

**Issue by BuddhiLW** [ch11ng/exwm#832]
In this build of DWM, I can use "Fullscreen mode" on a video, and it will fit that window. Is there an analogous on EXWM?

https://user-images.githubusercontent.com/59554283/116637294-dcf1db80-a939-11eb-80b6-1d7b02d1c463.mp4

**Comment by emysliwietz** [comment]
As far as I know, dwm ignores EWMH fullscreen requests of clients by default. A browser rescales itself to fullscreen mode without dwm displaying that window fullscreen. Exwm adheres to EWMH, so I doubt there's a way to change this behavior without changing any code. 
There are some workarounds, though
- In Firefox, navigate to `about:config` and toggle `full-screen-api.ignore-widgets` to `true`.
- In Qutebrowser, set `content.windowed_fullscreen` to `True`.
- In Chrome(ium)/Brave, there are a few addons that achieve the same like [this](https://chrome.google.com/webstore/detail/fullscreen-anything/olcfgpmjldkkjdclidhcbonieibfhhdh) and [these](https://chrome.google.com/webstore/search/YouTube%20Windowed%20FullScreen). I do not use any of these, so use them at your own risk.

**Comment by NerdThatsBadAtCode** [comment]
I have this same desire coming from Xmonad, but unfortunately these hacks won't work as well for me. I currently use the Brave Browser and watch Youtube on a Site Specific Browser, I have tried these full window extensions but I've noticed that these fail to remove the title bar at the top of the screen as pictured below. 
![2021-07-25-142439_1920x1080_scrot](https://user-images.githubusercontent.com/53658805/126909391-8f99c714-f3d8-4242-96e2-1ac455b6bf94.png)

Firefox does not have this issue when toggling `full-screen-api.ignore-widgets`, however, Firefox has its own issue where pausing and playing a video causes it to buffer indefinitely until I pause and play it again. 

I'm pretty new to EXWM and Emacs in general but I'm willing to dive into the code to fix this to maximize my screen real estate. I understand that the problem is that EXWM catches the EWMH and then switches its layout to full-screen, however, I am not sure how I can detect this and prevent it. I have looked through the apropos variables for EXWM hooks but I didn't find anything that seemed helpful. It seems to me that the problem may be fixed by changing the way that the full-screen message is handled in lines 539-564 of exwm.el or by removing the possibility of EXWM receiving the message by commenting out lines 677 and 691 of exwm.el. Unfortunately, I'm not sure how to implement these changes in my Emacs.org file(I am using a literate config file and am using EXWM with use-package if that helps). 

Thank you for your help in advance :)
