### ISSUE TITLE
Prevent other programs from executing emacs in EXWM

### ISSUE THREAD

**Issue by heeh** [ch11ng/exwm#882]
For example, `git commit -m "foo"` in a terminal triggers a default text editor(emacs in my case).
However, we are already using emacs in EXWM. How could I prevent other programs from executing emacs inside emacs?
Instead, I would like to open a new buffer.

We could try `emacs-daemon` and `emacsclient` but this seems silly because we run emacs all the time during the whole session.

**Comment by walseb** [comment]
I have the same issue when clicking email links. Emacs sets itself as the default email client so whenever I click one in chrome it launches emacs. I'm using emacs as a email client so I would prefer if it just opened up message-mode in the current emacs instance.

**Comment by eval-on-point** [comment]
What is the problem with using `emacsclient`? That works very well for me.

I have my `EDITOR` point to this shell script and it works fine:

```
#!/usr/bin/env bash

emacsclient -e '(find-file-other-window "'$1'")'
inotifywait -e close $1
emacsclient -e '(kill-buffer (get-file-buffer "'$1'"))'
```

@walseb, I think there is probably a similar solution where you just need to point your system's default mail handler to a similar script.

The above script may not handle all use cases but it should be enough to get you started.

**Comment by heeh** [comment]
Thanks. I just learned that we can use `emacsclient` without running `emacs-daemon`. It works.
```shell
inotifywait -e close $1
emacsclient -e '(kill-buffer (get-file-buffer "'$1'"))'
```
Could you explain what the second and third line do?

**Comment by eval-on-point** [comment]
The first line waits for the file that was opened to be receive the CLOSE event. In particular, this will wait until we save our emacs buffer. The second line kills the buffer once we have written it.

This allows commands that wait for you to edit a file (e.g. `git commit`) to know when you have finished editing it. You signal that you have finished editing by writing the buffer. You only need this if you are running `emacsclient -e ...`, which does not until you are done editing the file. If you simply set `EDITOR=emacsclient` it should block automatically as documented in the `emacsclient` manpage.

After thinking about this some, I think that it would be smarter to specify where the window is placed in my emacs configuration rather than this shell script, because `emacsclient` has more robust wait logic through the `(server-edit)` command.

**Comment by heeh** [comment]
That was helpful. Thank you again!
