### ISSUE TITLE
M-x: Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument numberp t)

### ISSUE THREAD

**Issue by iT-Boyer** [ch11ng/exwm#909]
when run M-x or recenterf file：
```
Error in post-command-hook (ivy--queue-exhibit): (wrong-type-argument numberp t) 
```
I use Doom , find this issue:
https://github.com/doomemacs/doomemacs/issues/3072

**Comment by ghost** [comment]
Heya @iT-Boyer I'm not a maintainer for this project but I know that if I were I would want some more information. Could you explain exactly under what conditions you encounter this error? It might also help if you were able to provide a minimal configuration that would allow someone to reproduce this issue. I say all of this because I'm afraid others might not be able to help you without this information

**Comment by medranocalvo** [comment]
The error does not seem related to EXWM.  I suggest reporting to Doom.

@jtamagnan-delphix, you are right that the report is... succinct, and that more information usually helps.  On the other hand, sometimes collecting the information is time consuming and as a user one is not sure what could actually help.  In principle all reports are appreciated (they can be quickly closed or more information can be asked), at least at the current rate.  Your trying to help is even more appreciated.  Thank you.
