### ISSUE TITLE
Dunst is only showing notifications when an EXWM window is focused

### ISSUE THREAD

**Issue by LemonBreezes** [ch11ng/exwm#925]
Hi. I have no idea what is causing this but for some reason, when I'm running Dunst, the notifications are only showing up once I focus an EXWM buffer.

**Comment by eval-on-point** [comment]
I do not have this issue on my NixOS machine, running Dunst as a systemd user service. I'm on EXWM Version 0.27.0.20230609.0 (commit a417f0d45e73f75028ba17ae49c664e3548deeba). How are you running dunst?

**Comment by LemonBreezes** [comment]
> I do not have this issue on my NixOS machine, running Dunst as a systemd user service. I'm on EXWM Version 0.27.0.20230609.0 (commit [a417f0d](https://github.com/ch11ng/exwm/commit/a417f0d45e73f75028ba17ae49c664e3548deeba)). How are you running dunst?

Hi. I'm using the latest commit of EXWM. I start Dunst in my `xinitrc` with `dunst &`. Maybe it's an issue with the latest EXWM only? I'm using Gentoo compiled with LLVM17.

**Comment by eval-on-point** [comment]
Thanks for the response. I dug in a little and see that my `dunst` is running as a SystemD user service.

`~/.config/systemd/user/dunst.service`:
```
[Service]
BusName=org.freedesktop.Notifications
Environment=
ExecStart=/nix/store/qiffadxy2rdwnmlqwwwzni6y4xsih73q-dunst-1.9.2/bin/dunst -config /home/m/.config/dunst/dunstrc
Type=dbus

[Unit]
After=graphical-session-pre.target
Description=Dunst notification daemon
PartOf=graphical-session.target
```

It similarly looks like the Arch linux installation of Dunst uses a SystemD service: [Arch Linux - dunst 1.9.2-1 (x86_64)](https://archlinux.org/packages/extra/x86_64/dunst/).

You might want to try creating a similar file to the one I have pasted above (which points to the correct config and dunst executable) and run `systemctl --user enable dunst` just to see what happens. If you don't want to use a SystemD service, you could also try launching `dunst` from within Emacs rather than in your `xinitrc` just to see what happens.

Last thing I would check are the logs from my X11 session for any interesting output from that `dunst &` call. Unsure exactly how to do that. Sorry I don't have much more info.

**Comment by medranocalvo** [comment]
I'm at a loss as to what could cause the notifications to appear only when focusing EXWM buffers.

@LemonBreezes, with "EXWM buffer" do you mean the buffers containing X windows?  Please try @eval-on-point's suggestions.

> If you don't want to use a SystemD service, you could also try launching `dunst` from within Emacs rather than in your `xinitrc` just to see what happens

@eval-on-point, I just released 0.28, could you test whether you experience the same issue with this version?  Thank you for helping out.

**Comment by eval-on-point** [comment]
On `0.28.0.20231006.0`, Dunst notifications appear visible to me when I select a vterm buffer and run `notify-send example notifcation`. It all appears to be working to me.

**Comment by LemonBreezes** [comment]
I just switched back to EXWM and deleted my Dunst configuration and the issue went away. I'm not sure yet what was causing this but there was something in my `dunstrc` that was being problematic with EXWM. I'll update this comment when I figure out what.

**Comment by LemonBreezes** [comment]
![image](https://github.com/ch11ng/exwm/assets/29102529/f870751e-d2ae-427e-8b09-7535ef25d09e)
Yup. It makes sense now. I did not notice these settings in the `pywal` template for Dunst.
