### ISSUE TITLE
X clients disappear on emacs restart

### ISSUE THREAD

**Issue by zevlg** [ch11ng/exwm#94]
Hello, I use `xwem-agent` ( https://github.com/zevlg/xwem/tree/master/xwem-agent ) to start Emacs from ~/.xinit, so my ~/.xinit looks like

<pre>
[...]
xterm&
firefox &
exec /home/lg/bin/xwem-agent -f /home/lg/.exwm/emacs.log emacs
</pre>

The idea behind `xwem-agent` is to hold X session (with all active X clients) and restart Emacs on its crashes/hangs/etc

However, if I simple `C-x C-c` from Emacs, my xterm and firefox become runnig, but unmaped, so next exwm start won't manage them

I use this hack in my `exwmrc.el`

<pre>
(defun lg-exwm-unmanage-all ()
  (mapc (lambda (e)
          (let ((win (car e)))
            (exwm-manage--unmanage-window win t)
            (xcb:+request exwm--connection
                (make-instance 'xcb:MapWindow :window win))
            (xcb:flush exwm--connection)))
        exwm--id-buffer-alist))

(add-hook 'kill-emacs-hook 'lg-exwm-unmanage-all)
</pre>

I think exwm should manage X clients in such a way, that after killing Emacs exwm would be able to manage them once again

thanks

**Comment by ch11ng** [comment]
Hi @zevlg,

I agree that it'd nice if EXWM can be restarted in-place, but there're two problems:

1. Because all X windows are currently reparented to Emacs frames, they should be reparented back to the root window on exit.  So the problem you encountered is not because the X windows are unmapped, but they're destroyed.  Your `lg-exwm-unmanage-all` actually solves this problem.
2. The other problem I have no solution yet is that `start-process`, `start-process-shell-command`, etc create subprocesses of Emacs, which will become orphans after Emacs exits.  Most applications are started this way, I'm afraid.

**Comment by ch11ng** [comment]
Hi @zevlg,

I think you'are right and we should unmanage all X windows on exit.  I've fixed it in 15cdf8f5897183adf5426ecc280eb61626e2c980.  Though as I've mentioned, this will only work for processes not created by Emacs.

**Comment by ch11ng** [comment]
FYI I've added `exwm-restart`.
